# Generated by Django 2.2.3 on 2019-08-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_auto_20190807_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='idea_pics'),
        ),
    ]
